### ISSUE TITLE
Implement CORS handling

### ISSUE THREAD

**Issue by cicnavi** [rediris-es/simplesamlphp-module-oidc#103]
Currently we don't support CORS handling (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), which affects JavaSript RPs. 

The problem is manifested when JS RP tries to do a cross-origin request, and it boils down to " ... the specification mandates that browsers "preflight" the request, soliciting supported methods from the server with the HTTP OPTIONS request method, and then, upon "approval" from the server, sending the actual request. Servers can also inform clients whether "credentials" (such as Cookies and HTTP Authentication) should be sent with requests. CORS failures result in errors, but for security reasons, specifics about the error are not available to JavaScript. All the code knows is that an error occurred. The only way to determine what specifically went wrong is to look at the browser's console for details..."

Problem noticed with JS OIDC client: https://www.npmjs.com/package/oidc-client

It's a bit tricky to test this since both OP and RP have to have valid TLS certs implemented (cross origin requests without proper HTTPS are limited by browsers). 

However, if one has RP with HTTPS, the problem can be quickly demonstrated using 'fetch' from browsers web console. For example, using fetch try to GET userinfo_enpoint with Authorization Bearer token header. This will trigger a preflight HTTP request, which will (currenlty) result in HTTP 500 on OP.

```
fetch('https://op.org/userinfo-endpoint', {
    method: 'GET', // *GET, POST, PUT, DELETE, etc.
    mode: 'cors', // no-cors, *cors, same-origin
    //credentials: 'include', // include, *same-origin, omit
    redirect: 'follow', // manual, *follow, error
    headers: {
       'Authorization': 'Bearer 123'
    },
  }).then(res => {console.log(res)}).catch(err => {console.log(err)});
```

![image](https://user-images.githubusercontent.com/3176844/118261798-5bab5480-b4b4-11eb-83cb-5ccbed304eb7.png)

A quick solution for HTTP OPTIONS request might be to return HTTP Header Access-Control-Allow-Origin: *, for example:
```
if ($request->getMethod() === 'OPTIONS') {
    // in real app return new Response() with proper headers
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Headers: *');
    header('Access-Control-Allow-Methods: POST, GET, OPTIONS');
    http_response_code(200);
    exit();
}
``` 

Another solution would be to enable clients to have authorized JS origins for every client, and then specify authorized origins in reponse. 

```
Access-Control-Allow-Origin: https://op.org
```

This is the way Google does it:
![image](https://user-images.githubusercontent.com/3176844/118263081-1851e580-b4b6-11eb-8246-aed97502a46c.png)

**Comment by sgomez** [comment]
Good catch! But this is only a problem for implicit/hybrid profile, isn't it?

**Comment by cicnavi** [comment]
I was thinking the same, and I think that is true in general. However the
mentioned JS client https://www.npmjs.com/package/oidc-client uses PKCE
enabled authorization code flow. So, it uses claims from ID token, however,
it also does an additional request to userinfo_endpoint by default.  It has
a config option to disable such behaviour ( loadUserInfo setting can be set
to false: https://github.com/IdentityModel/oidc-client-js/wiki).
I think it does so since the spec says that the userinfo_endpoint can
return claims defined in Section 5.1
<https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims>, as
well as additional Claims not specified there (
https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.3.2).
Like, it tries to ensure that it gathers all claims that might be
available...


-- 

Marko Ivančić
https://markoivancic.from.hr
