### ISSUE TITLE
Response to ImplicitFlow should not send an access_token in lib/Server/Grants/ImplicitGrant.php

### ISSUE THREAD

**Issue by dlgroep** [rediris-es/simplesamlphp-module-oidc#128]
(this is an issue against branch fix/namespaces ...)

When requesting an id_token through Implicit flow (like 
`https://sso.nikhef.nl/sso/module.php/oidc/authorize.php?response_type=id_token&scope=openid%20email%20assurance&client_id=_f6bfe81892e680e4ecfc3b41ecf1a15d141c0d106b&state=IV1GnS19OVY5_GGCh7tYPGgJZ7M&redirect_uri=https%3A%2F%2Fhekel.nikhef.nl%2Frp%2Fredirect_uri&nonce=MUSS8S7yheICeK4OcLqg6r1EYuXpqs6kaetpbLqyPck`), the response includes *also* an access_token besides the requested id_token:

```
Raw message:
<access_token>eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJfZjZiZmU4MTg5MmU2ODBlNGVjZmMzYjQxZWNmMWExNWQxNDFjMGQxMDZiIiwianRpIjoiYWM2NDhiOTU2NjM3MDQyOGYwYzA1ZWYwNTBiZmE1MzQzNmYzYTZiYTZkMjEzOTQyYTZmNGViYTE2N2UyMzYwMDM3NGZiMTMwODk3MWY1OWQiLCJpYXQiOjE2Mjg4NTgzNTEuNTU5NjcyMSwibmJmIjoxNjI4ODU4MzUxLjU1OTY3NTksImV4cCI6MTYyODg2MTk1MS41NTQzMTYsInN1YiI6IjQwZWE2MjFhMGE3MzU1Y2Y0ZmIxY2E4ZDRmMjJhNTNkQG5pa2hlZi5ubCIsInNjb3BlcyI6WyJvcGVuaWQiLCJlbWFpbCIsImFzc3VyYW5jZSJdfQ.c_EDLMwhigKfgTJljzR-Ksu3RFCcBuHaHyAwyfDJmMhPOpVZ5Pkr5Jf7NtWnViJw-so28NoszP7jAqBnakatVaqx6n_CQAuZc1OgCl0GHBhN6kNEz_vYFj0cBkDXnl4-vOVhDiRBft17TnpegdaF21E-pAUClge-eylu-KKBgnFa6-GI4ejrwTebmIlYpRFAEJhv5pDSH5rkMkhxoA196YtvRVL6t0-mRe854SkthfSvjeDDS8cqwpnM_-ijjQycrCm_S15Acs7fUJSWYaLzu0QAWtTc2QyZB92l7XZcK6A3tOC-Vzge6HFFOSuSDMfaBMgDK7xm3U4i4R1O9JRE2w</access_token>
<expires_in>3600</expires_in>
<id_token>eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEwOTA4ZjUzYmYxNThmYzgxZWFjMTE2MDMzYTk5YjJlIn0.eyJpc3MiOiJodHRwczovL3Nzby5uaWtoZWYubmwiLCJhdWQiOiJfZjZiZmU4MTg5MmU2ODBlNGVjZmMzYjQxZWNmMWExNWQxNDFjMGQxMDZiIiwianRpIjoiYWM2NDhiOTU2NjM3MDQyOGYwYzA1ZWYwNTBiZmE1MzQzNmYzYTZiYTZkMjEzOTQyYTZmNGViYTE2N2UyMzYwMDM3NGZiMTMwODk3MWY1OWQiLCJuYmYiOjE2Mjg4NTgzNTEsImV4cCI6MTYyODg2MTk1MSwic3ViIjoiNDBlYTYyMWEwYTczNTVjZjRmYjFjYThkNGYyMmE1M2RAbmlraGVmLm5sIiwiaWF0IjoxNjI4ODU4MzUxLCJub25jZSI6Ik1VU1M4Uzd5aGVJQ2VLNE9jTHFnNnIxRVl1WHBxczZrYWV0cGJMcXlQY2siLCJlbWFpbCI6ImRhdmlkZ0BuaWtoZWYubmwiLCJlZHVwZXJzb25fYXNzdXJhbmNlIjoidXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFjOmNsYXNzZXM6UGFzc3dvcmRQcm90ZWN0ZWRUcmFuc3BvcnQiLCJhbXIiOiJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YWM6Y2xhc3NlczpQYXNzd29yZFByb3RlY3RlZFRyYW5zcG9ydCIsImFjciI6Imh0dHBzOi8vcmVmZWRzLm9yZy9wcm9maWxlL3NmYSJ9.gbLjxBjnQnvcot93omq9qwNToY4BZKx0ytcGZH-WVicb7DmuUbTkXjG0TJgU-3SuuaI0MGPdmrQcvQtIkiIpIbkrGGG2Za5Bq6WRTO-r0B1KjtDrnjszL6sU5PfQ-kNpiv5VNuTj1Ku5XC4iqgSfHUiQxADoWKYOq8KRuAz1YqQ-igbFR-Js93HL3tlkaYJymVuAc63WN-OpA6D9TGFwqBan2iNtP5nmqpUcHdF5_LMvt1euy0T0mOce55EJX7hDx_8cLz51oW-2pKIqi09lyjU-33Ar8mwsI2OFUalW9NvQmgVCWzWm0rw59iT9z-oDjxv-Ep3si3D6Iq7zgbDKtg</id_token>
<response_mode>fragment</response_mode>
<state>IV1GnS19OVY5_GGCh7tYPGgJZ7M</state>
<token_type>Bearer</token_type>
```

This makes `mod_auth_openidc` go ape, since it strictly follows https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest that says: "No Access Token is returned when the value is id_token. ". (see e.g. https://github.com/zmartzone/mod_auth_openidc/issues/81)

Commenting out sending the access token on line 136 of "lib/Server/Grants/ImplicitGrant.php" fixes this - and AFAIK this code is only used in the ImplicitFlow.

The attach diff is tested to solve this specific issue (not extensively tested, but ought to match the OIDC core spec - after this patch code flow tested to still work fine):
[implicit_grant_fix_access_token.diff.txt](https://github.com/rediris-es/simplesamlphp-module-oidc/files/6982466/implicit_grant_fix_access_token.diff.txt)

mod_auth_openidc apache config to reproduce:
```
OIDCProviderMetadataURL https://sso.nikhef.nl/.well-known/openid-configuration
OIDCClientID MYCLIENT
OIDCClientSecret SECRET
OIDCRedirectURI https://hekel.nikhef.nl/rp/redirect_uri
OIDCCryptoPassphrase PASSPHRASE
OIDCResponseType "id_token"
OIDCScope "openid"

<Location /rp/>
   AuthType openid-connect
   Require valid-user
</Location>
```

**Comment by cicnavi** [comment]
Thanks for reaching out. 'fix/namespaces' branch is mostly for PSR-4 compatibility. We have another branch in which we tackle several implicit flow issues:  'feature/idtoken-claims'. Care to try your use case using that branch? It's in pull request: https://github.com/rediris-es/simplesamlphp-module-oidc/pull/124)

**Comment by dlgroep** [comment]
Hi Marco, 
I cannot readily test that branch directly since the operational environment this lives in requires 'usenewui' and thus PSR-4, but looking at the code of the idtoken-claims branch, the inclusion of the access token  does look to have a `$addAccessTokenHashToIdToken = false;` set by false default unless `if ($authorizationRequest->shouldReturnAccessTokenInAuthorizationResponse()) {` -- which depends on the incoming request - which looks fine.

Sorry for not being able to test, but looking at the code this issue seems already solved in that branch. Thanks!
