### ISSUE TITLE
idToken algorithm is RS256 but kid header is missing

### ISSUE THREAD

**Issue by voidloop** [rediris-es/simplesamlphp-module-oidc#15]
Hi, when I try your module with the tool "OpenID Connect Playground" on https://openidconnect.net/, the step "Verify User Token" fails with the mysterious message "There was an error verifying your token. Try again".

With the Firefox's Web Developer tool "Network", I can see that the response of the request to verify the id_token is "idToken algorithm is RS256 but kid header is missing". In fact in the jwt.io debugger, the "kid" claim in the header is missing. I know that this claim is optional, but how I can add this claim in the JWT header using simplesamlphp-module-oidc?
In general how can I add or remove claims in the header? Thank you.

**Comment by sgomez** [comment]
Hi @voidloop,

Sorry for the late reply. I'm going to investigate it and I hope to tell you something ASAP.

**Comment by sgomez** [comment]
Hi again @voidloop, 

The point is, we need to have the same kid in the header of the JWT and in the JWKS response, not just in the JWT header.

This module only has one key (by the moment there are no reason to have more than one), so I can to add it directly in the JWKS and in the JWT header.

I'll do my best to do a PR with this today.
