### ISSUE TITLE
id_token iss is independent from the module and not compliant with oidc

### ISSUE THREAD

**Issue by daserzw** [rediris-es/simplesamlphp-module-oidc#16]
Hi, doing some debugging I've discovered that the iss in the id_token is ALWAYS an http URL, and it is also independent from the issuer published in the provider metadata at /.well-known/openid-configuration. Actually the spec define the value of `iss` as an https URL, not http [1].

Digging a little bit I've found that the problem seems to be the `oauth2-openid-connect-server` library, in the `IdTokenResponse.php`:

~~~
[..]
        // Add required id_token claims
        $builder = (new Builder())
            ->setAudience($accessToken->getClient()->getIdentifier())
            ->setIssuer('http://' . $_SERVER['HTTP_HOST'])
            ->setIssuedAt(time())
            ->setExpiration($accessToken->getExpiryDateTime()->getTimestamp())
            ->setSubject($userEntity->getIdentifier());

[..]
~~~

I will fire a PR to the library owner to fix this, but there is another problem: the oidc core spec at 3.1.3.7 [2], says "The Issuer Identifier for the OpenID Provider (which is typically obtained during Discovery) MUST exactly match the value of the iss (issuer) Claim.". So, it would be a good idea to have the issuer passed from your module to the library, in that way no mismatch would be possible. If you are ok with that, I will create a PR accordingly.

Cheers,
Davide

[1] https://openid.net/specs/openid-connect-core-1_0.html#IDToken
[2] https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken

**Comment by amaccuish** [comment]
Is there an update to this? oauth2-proxy which uses go-oidc does not allow iss to differ from the discover the url and will not accept changes to allow this.

**Comment by cicnavi** [comment]
@amaccuish this is solved in master and v1.0. The issuer is now generated dynamically...

**Comment by amaccuish** [comment]
I tried master and iss is still just the hostname and not the discover url. How would I be able to change this? I couldn't find where in the code this is generated

**Comment by cicnavi** [comment]
Specification does not state that the issuer should be the discovery URL. Requiring that it does seems to go against the spec and is to restrictive in my opinion... The discovery document has a property that states the issuer, so I don't understand why would and package require that the issuer property in discovery document be the same as the discovery URI... Are you sure you are getting that error?

From https://openid.net/specs/openid-connect-core-1_0.html
```
Issuer Identifier
    Verifiable Identifier for an Issuer. An Issuer Identifier is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components. 
```

It is generated like this https://github.com/simplesamlphp/simplesamlphp-module-oidc/blob/1fb82bd84bf6917016aac2997d6c2bdf038fd05e/lib/Services/OidcOpenIdProviderMetadataService.php#L36

**Comment by amaccuish** [comment]
So the issue I am having is related to https://github.com/coreos/go-oidc/issues/159

The spec part they quote says:

> The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer.

**Comment by cicnavi** [comment]
Hm... and which discovery URL are you using? 

Maybe the problem is that the package expects that the discovery URL is in a form `<issuer_url>/.well-known/openid-configuration`. Note that issuer URL is not the same as discovery URL. 

Check our readme on how to create a "well-known" version of discovery URL, it has an example for nginx. 

Also, it seems that there is a config option for you to manage this check: https://github.com/coreos/go-oidc/pull/195
