### ISSUE TITLE
simplesamlphp 1.17 support?

### ISSUE THREAD

**Issue by madsi1m** [rediris-es/simplesamlphp-module-oidc#27]
Hi in simplesamlphp 1.17 i am having trouble getting the twig templates to render. Any chance to support simplesamlphp 1.17?

In my config I set up database and 'language.i18n.backend' => 'gettext/gettext', as instructed in the README.md

Cheers
Michael

**Comment by tvdijen** [comment]
Have you set `usenewui => true` as well?
I see it's not mentioned in the readme...

**Comment by madsi1m** [comment]
Ah, very good. Cheers
