### ISSUE TITLE
iss not sent?

### ISSUE THREAD

**Issue by madsi1m** [rediris-es/simplesamlphp-module-oidc#28]
Hello, I am having issues with this module and my oidc client. It tells me that i am not sending the `iss` (issuer) as per https://openid.net/specs/openid-connect-core-1_0.html#IDToken 

I am not sure if the problem is here or on my service provider.

How do i confirm that simplesamlphp is sending an `iss` along side of the `sub`?

Thank you for your patience.

**Comment by madsi1m** [comment]
testing with https://openidconnect.net i get invalid signature. Am i doing something wrong?

**Comment by sgomez** [comment]
Hi, the issuer is sent. But this plugin is not yet fully openid connect complaint. It just have the minimal attributes to be able to identify a client.

I need to update this module with last libraries dependencies and improve it with the new functionalities. But right now I have not time to work in this. I can not tell you when this will be resolved. Sorry.

**Comment by madsi1m** [comment]
thank you!
