### ISSUE TITLE
Admin link under Tools not visible

### ISSUE THREAD

**Issue by restena-sw** [rediris-es/simplesamlphp-module-oidc#35]
This is a follow-up to the issue https://github.com/sgomez/simplesamlphp-module-oauth2/issues/15 where I had the same issue. With Twig, the new admin area does not display any links towards the OIDC configuration pages.

On the old project, the response was "Anyway, this issue with newui happens too with the oidc module, because a BC with Twig template. It is resolved in master branch and I hope to release a new version next week. I need to do some more tests."

I am now using master branch of the rediris-es/simplesamlphp-module-oidc and still don't see those links.

While it would be great if this bug could be fixed, for the moment I'd be happy enough with a workaround: what exactly are the URLs in question so I can browse to them manually?

**Comment by bziraoui** [comment]
Hello, I have the same issu, Have you find for workaround ?

**Comment by restena-sw** [comment]
I got a bit further with the following two tricks/observations:

1) recent versions of simpleSAMLphp use the config keywords store.sql.(dsn|username|password). But the OIDC module insists on getting the values from database.(dsn|username|password). So I copy&pasted the values into these "new" config items.
2) to find out the URL to go to, I first set usenewui = false, went to the old admin page and noted its URL. Then I turned on usenewui again and went to that same URL. It should be SSP_base_url/module.php/core/frontpage_welcome.php

At that point the database upgrade from the old sgomez plugin was triggered; it would create new tables etc. on a fresh installation. So that gets most of the bootstrap job done.

This yielded an admin page with Federation -> "Array" which actually led to

SSP_base_url/module.php/oidc/install.php

and then things continue from there.

**Comment by restena-sw** [comment]
Well, trying to create a new client then bails out with:

[6a83eaaf05] SimpleSAML\Error\Exception: Error 1 - Call to a member function getData() on null at .../simplesamlphp-1.18.5/modules/oidc/lib/Form/Controls/CsrfProtection.php:39

So not quite done yet, but a different problem.

**Comment by andres-blanco** [comment]
there are some syntax errors in master branch: https://github.com/rediris-es/simplesamlphp-module-oidc/pull/36/files#diff-bdf41d62d68ca4933d9f156a9b0dd56eR26. 

I resolved them in this PR https://github.com/rediris-es/simplesamlphp-module-oidc/pull/36

**Comment by restena-sw** [comment]
The PR indeed fixes all the syntax errors. The only thing it doesn't fix is that the initial link to the OIDC admin module is still not visible under "Federation". But since there's an easy workaround earlier in this issue, that's half as bad.

**Comment by sgomez** [comment]
Please try with this release

https://packagist.org/packages/rediris-es/simplesamlphp-module-oidc#v1.0.0-rc.3
