### ISSUE TITLE
SimpleSAML\XHTML\Template::findTemplatePath ignore .twig files

### ISSUE THREAD

**Issue by puggan** [rediris-es/simplesamlphp-module-oidc#37]
I got the error:
Template: Could not find template file [oidc:install.twig] at [/var/simplesamlphp/modules/oidc/templates/install.twig]

from SimpleSAML\XHTML\Template::findTemplatePath() in lib/SimpleSAML/XHTML/Template.php:639

findTemplatePath() tries to find `install.twig.php` or `install.twig.tpl.php`, but ignores `install.twig`

**Comment by tvdijen** [comment]
Hi @puggan ! What version of SSP are you using and are you using the old or new UI?

**Comment by puggan** [comment]
The dockerfile contains thus 2 row, with versions:
composer create-project --no-dev simplesamlphp/simplesamlphp:1.18.5
composer require rediris-es/simplesamlphp-module-oidc v1.0.0-rc.1

So guess we use SSP 1.18.5.

Have no idé about the UI, the only part of the UI I use is the authentication test,
if it's a visible difference maybe you can see if its old or new at:
https://scoutid.se/simplesaml/module.php/core/authenticate.php

**Comment by tvdijen** [comment]
Yeah, that's the old one...
SimpleSAMLphp has an old UI that is still the default right now, and a new UI based on Twig-templates that is optional, but will be the only option in a future release.
This module only has Twig-templates and does not support the old UI..

Easiest for you to do is to add `'newui' => true` in the config.php, or hope someone will take the effort to add the legacy templates to this module..

**Comment by puggan** [comment]
Could you add a row about the newui-settings in the readme-file?

**Comment by tvdijen** [comment]
I would if I could :) But I'm sure Sergio will do it for you

**Comment by sgomez** [comment]
Please try with this release:

https://packagist.org/packages/rediris-es/simplesamlphp-module-oidc#v1.0.0-rc.3
