### ISSUE TITLE
Processing filters not being executed

### ISSUE THREAD

**Issue by andres-blanco** [rediris-es/simplesamlphp-module-oidc#38]
I've noticed that the processing filters are not being executed. I don't think this behaviour is OK given the processing might change user Attributes.

Is this behaviour intended or is it a bug?

Thanks!

**Comment by tvdijen** [comment]
Could be a similar case to this one;
https://github.com/simplesamlphp/simplesamlphp/issues/1250

**Comment by andres-blanco** [comment]
simplesamlphp/simplesamlphp#1250 seems to be an error while executing the ProcessChain, in this case, the processing chain is not being executed at all.

It appears from looking at simplesamlphp code, that the chain processing code is being called from the method `SimpleSAML\IdP::postAuth` https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.18/lib/SimpleSAML/IdP.php#L329. This method is called in a normal saml flow because it's being saved in the state before initiating the login. This is a screenshot of the dump of the state entering an SAML SP:
![image](https://user-images.githubusercontent.com/375980/80923300-304a4180-8d59-11ea-96b1-5b6b6a75f15c.png)
When entering to the login form from an OIDC Flow, this keys just point to the authorize endpoint that triggered the login:
![image](https://user-images.githubusercontent.com/375980/80923334-6ab3de80-8d59-11ea-9e61-c9c6dbde8037.png)

**Comment by sgomez** [comment]
I'm going to close this issue. I think it is not related with this module but SimpleSAMLphp.
