### ISSUE TITLE
kid in issued JWT does not match kid in jwks

### ISSUE THREAD

**Issue by craftbyte** [rediris-es/simplesamlphp-module-oidc#50]
The `kid` in an issued JWT is `0` while the jwks endpoint sets the `kid` to `oidc`.
I believe the issue is here: https://github.com/rediris-es/simplesamlphp-module-oidc/blob/master/lib/Server/ResponseTypes/IdTokenResponse.php#L110

**Comment by sgomez** [comment]
This should be fixed in #46
