### ISSUE TITLE
How to get attributes added by processing filters put in authproc.idp

### ISSUE THREAD

**Issue by jbouzekri** [rediris-es/simplesamlphp-module-oidc#53]
In SimpleSamlPHP, you can add authentication processing filters in keys `authproc.idp` of the `config.php`

It can be useful to add custom attributes with a bit of coding by adding custom filters. For example this one which adds all the groups the user is a member of in ldap :

```
55 => array(
                      'class' => 'ldap:AttributeAddUsersGroups',
                      'authsource' => 'ldap',
                      'attribute.username' => 'entryDN',
                      'attribute.member'   => 'cn',
                      'attribute.memberof' => 'member',
                  ),
```

However I am unable to get back attributes which are added by these filters when I log in through OIDC.

I added a `var_dump/die` in the process method of the above filter and it is never executed when I use OIDC. It is when I log in through SAML.

**Comment by lblatlaswiki** [comment]
I would second this request.

I run SimpleSamlPHP as an IdP proxy, connecting our SPs with a federated login.  I think this is a fairly common usage mode.
The federation provides authentication and a small number of attributes.  We augment that with organization specific attributes from a local LDAP directory.  
When we connect to our IdP proxy with SAML, we can use these attributes through the authproc.idp rules.  But it seems that the oidc module doesn't look at this expanded set of attributes, but only the ones that come directly from the federation IdPs.  This is very limiting.

**Comment by tvdijen** [comment]
I think this is going to be quite challenging because of the way this module was set up.. It's completely bypassing the authsource-mechanism

**Comment by lblatlaswiki** [comment]
Ah.  Well, that is unfortunate.
I didn't necessarily expect that the module could parse my authproc rules, but thought that there may be some mechanism in the configuration file, where the OIDC-SAML translation rules are specified, of modifying attributes/claims.   Good to know it isn't implemented, so I don't spend more time looking for it.

**Comment by tvdijen** [comment]
It's an observation and I wouldn't just take my word for it.. Perhaps Sergio sees an opportunity to incorporate this functionality

**Comment by cicnavi** [comment]
I would also benefit from this, I need to implement existing fticks logging authproc... 

From what I can see, the class SimpleSAML\Auth\ProcessingChain would be used for this. @tvdijen is there anything specific you see for blocking other than that the ProcessingChain is not used? I think I'll have some spare time later this month, so maybe I could take a look at this and make another pull request...

**Comment by cicnavi** [comment]
I have made a new pull request: https://github.com/rediris-es/simplesamlphp-module-oidc/pull/63

**Comment by jdanderson3** [comment]
I see that this pull request has not been accepted yet.   Can we assume that it won't be?

**Comment by sgomez** [comment]
@jdanderson3 the PR #63 was merged, but you will need to use dev-master until we can release a new stable version.
