### ISSUE TITLE
openid-configuration.php fails asking for option pkce

### ISSUE THREAD

**Issue by lblatlaswiki** [rediris-es/simplesamlphp-module-oidc#59]
I am running simplesamlphp 1.19.0-rc1

I install simplesamlphp-module-oidc with composer:
'composer require rediris-es/simplesamlphp-module-oidc'

The install seems to work.  The database schema are created and I am able to add an OpenID Connect Client.

But when I attempt to view the endpoint URLs with
https://mydomain/simplesaml/module.php/oidc/openid-configuration.php

I get

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: /opt/simplesamlphp-1.19.0-rc1/config/module_oidc.php: Could not retrieve the required option 'pkce'
Backtrace:
6 lib/SimpleSAML/Configuration.php:454 (SimpleSAML\Configuration::getValue)
5 lib/SimpleSAML/Configuration.php:685 (SimpleSAML\Configuration::getBoolean)
4 modules/oidc/lib/Controller/OpenIdConnectDiscoverConfigurationController.php:37 (SimpleSAML\Modules\OpenIDConnect\Controller\OpenIdConnectDiscoverConfigurationController::__invoke)
3 modules/oidc/lib/Services/RoutingService.php:52 (SimpleSAML\Modules\OpenIDConnect\Services\RoutingService::call)
2 modules/oidc/www/openid-configuration.php:18 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

**Comment by cicnavi** [comment]
Take a look at https://github.com/rediris-es/simplesamlphp-module-oidc/issues/57.

**Comment by lblatlaswiki** [comment]
Thanks.   I didn't think to view the closed issues.
