### ISSUE TITLE
Support wildcards in redirect URI

### ISSUE THREAD

**Issue by n0emis** [rediris-es/simplesamlphp-module-oidc#62]
It would be really helpful to have a way to allow wildcards in redirect uris.

For example the following:
```
https://*.secure.example.com/_oauth/callback
https://secure.example.com/*
```

**Comment by sgomez** [comment]
Sorry, the OAuth RFC discourages this behaviour:

https://tools.ietf.org/html/draft-ietf-oauth-security-topics-14#page-11

Thanks for your suggestion anyway.
