### ISSUE TITLE
Conformance Warning: oidcc-refresh-token.  discovery document should say we support refresh token gran type

### ISSUE THREAD

**Issue by pradtke** [rediris-es/simplesamlphp-module-oidc#73]
I'm making issues to track some of the conformance test gaps. We can prioritize later.

Conformance tests "The server issued a refresh token but does not claim to support this grant type (grant_types_supported in not present in the discovery document)"

The OIDC spec  (https://openid.net/specs/openid-connect-discovery-1_0.html#rfc.section.3) says `grant_types_supported` is optional, and if not set it means `["authorization_code", "implicit"]`.  We also support refresh tokens. We should explicitly set `grant_types_supported`

**Comment by cicnavi** [comment]
Great catch! Related to that, what do you guys think that we enable grants from config? Currently we have hard coded OIDC authorization code flow, OAuth2 implicit flow and refresh token flow. 
We could introduce config option to enable admins to choose which grants they want to enable, if you think this is valuable.
