### ISSUE TITLE
sql dependency?

### ISSUE THREAD

**Issue by ctr49** [rediris-es/simplesamlphp-module-oidc#76]
The installation instructions mention the requirement to configure sql. However, #12 and #45 seem to indicate that phpsession can also be used as store. Can you please clarify?

When enabling oidc while using phpsession I receive an error `Could not retrieve the required option 'database.dsn'` (from DatabaseMigration.php).

This is with simplesamlphp-module-oidc 1.0.0 (installed via composer) on simplesamlphp 1.18.8 with PHP 7.3.27-1~deb10u1 on a Debian Buster system.

**Comment by sgomez** [comment]
Hi. This module requires SQL to store client and tokens metadata. This is different from user sessions that can be stored with PHP session, memcache, SQL or Redis.

See 'database.dsn' and 'store.type' parameters in simplesamlphp/config/config.php. You need to configure both.

**Comment by pradtke** [comment]
Hi @zoghlamikaiseruqam 

This module doesn't use `store.type`. It uses the the various `database.` settings to determine the DB, username, password, etc.

You can leave `'store.type'  => 'memcache'` and just set the `database.` settings.  We run it with that combination.

**Comment by zoghlamikaiseruqam** [comment]
Hi,
Thank you for your help! It seems that it was a misconfiguration on our end. It's now working! Thank you again
