### ISSUE TITLE
Server returns an invalid error message after we try to use an authorization code for a second time

### ISSUE THREAD

**Issue by sgomez** [rediris-es/simplesamlphp-module-oidc#92]
According https://tools.ietf.org/html/rfc6749#section-5.2

If we tray to get a access token for a second time "invalid_grant" error should be returned. Instead of that we return a "invalid_request" error.

**Comment by sgomez** [comment]
Partially fixed in #114 
Now returns a warning

**Comment by cicnavi** [comment]
There is no warning anymore, error is properly returned as JSON. Probably solved when merged with other fixes related to showing error messages.
