### ISSUE TITLE
Not compliant behaviour when response_type parameter is missed

### ISSUE THREAD

**Issue by sgomez** [rediris-es/simplesamlphp-module-oidc#97]
The authorization server must either redirect back with an 'unsupported_response_type' or 'invalid_request' error, or must display an error saying the response type is missing.

Now the AS returns inappropriate error code 'unsupported_grant_type'

See: https://tools.ietf.org/html/rfc6749#section-3.1.1

**Comment by cicnavi** [comment]
Possible solution: https://github.com/rediris-es/simplesamlphp-module-oidc/commit/a20645c1cc3de0689da6ebf49d66329a25f0fddc

**Comment by cicnavi** [comment]
Fix in #107
